/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-11-07 00:55:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.saii.signup;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signupPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<title>회원가입 입력</title>\r\n");
      out.write("<style>\r\n");
      out.write("	#form {width: 400px; margin:auto; padding:30px}\r\n");
      out.write("	h2 { text-align: center; margin: 30px 0 30px 0;}\r\n");
      out.write("	input[type=text], input[type=password] { vertical-align: 5px; width:400px; height:40px; display: inline-block;\r\n");
      out.write("									border:none; background: #F7F7F7;}\r\n");
      out.write("	\r\n");
      out.write("	label { vertical-align: 5px; color: #999;}\r\n");
      out.write("	a {vertical-align: 5px;}\r\n");
      out.write("	select {vertical-align: 6px; width: 80px; height:30px;}\r\n");
      out.write("	\r\n");
      out.write("	.button {padding: 0; border: none; border-radius:5px;  font: inherit;\r\n");
      out.write("  			color: inherit; background-color: #EDEDED; cursor: pointer;}\r\n");
      out.write("	\r\n");
      out.write("	.ck-button {margin:0; border:none; overflow:visible; border-radius:0; display:inline-block;\r\n");
      out.write("				vertical-align: middle; font-size: 0.8rem; line-height: 38px; text-align: center;\r\n");
      out.write("    			text-decoration: none; text-transform: uppercase; transition: 0.1s; \r\n");
      out.write("    			transition-property: color, background-color, border-color;\r\n");
      out.write("    			background-color:#EDEDED;\r\n");
      out.write("    			width: 60px !important; }	\r\n");
      out.write("    			\r\n");
      out.write("    div {padding: 0px 0px 8px 0px;}			\r\n");
      out.write("    			\r\n");
      out.write("    div.ckck {display: flex;}\r\n");
      out.write("    \r\n");
      out.write("    input.sign {margin-top: 24px; height: 45px; width: 100%; background: none; border: none;\r\n");
      out.write("    		color: #fff; font-size: 16px; font-weight: 500; cursor: pointer;\r\n");
      out.write("    		border-radius: 4px; background-color: #98dde3;}\r\n");
      out.write("    		\r\n");
      out.write("    \r\n");
      out.write("	\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("	//생년월일 받기\r\n");
      out.write("	$(document).ready(function(){            \r\n");
      out.write("	    var now = new Date();\r\n");
      out.write("	    var year = now.getFullYear();\r\n");
      out.write("	    var mon = (now.getMonth() + 1) > 9 ? ''+(now.getMonth() + 1) : '0'+(now.getMonth() + 1); \r\n");
      out.write("	    var day = (now.getDate()) > 9 ? ''+(now.getDate()) : '0'+(now.getDate());           \r\n");
      out.write("	    //년도 selectbox만들기               \r\n");
      out.write("	    for(var i = 1960 ; i <= year ; i++) {\r\n");
      out.write("	        $('#year').append('<option value=\"' + i + '\">' + i + '</option> ');    \r\n");
      out.write("	    }\r\n");
      out.write("\r\n");
      out.write("	    // 월별 selectbox 만들기            \r\n");
      out.write("	    for(var i=1; i <= 12; i++) {\r\n");
      out.write("	        var mm = i > 9 ? i : \"0\"+i ;            \r\n");
      out.write("	        $('#month').append('<option value=\"' + mm + '\">' + mm + '</option> ');    \r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	    // 일별 selectbox 만들기\r\n");
      out.write("	    for(var i=1; i <= 31; i++) {\r\n");
      out.write("	        var dd = i > 9 ? i : \"0\"+i ;            \r\n");
      out.write("	        $('#day').append('<option value=\"' + dd + '\">' + dd+ '</option> ');    \r\n");
      out.write("	    }\r\n");
      out.write("	    $(\"#year  > option[value=\"+year+\"]\").attr(\"selected\", \"true\");        \r\n");
      out.write("	    $(\"#month  > option[value=\"+mon+\"]\").attr(\"selected\", \"true\");    \r\n");
      out.write("	    $(\"#day  > option[value=\"+day+\"]\").attr(\"selected\", \"true\");       \r\n");
      out.write("	  \r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	 \r\n");
      out.write("	function nickCk(){           \r\n");
      out.write("		/* if(form.nickname.value == \"\"){\r\n");
      out.write("			alert(\"닉네임을 입력하세요\");\r\n");
      out.write("			form.nickname.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		//닉네임 길이 체크 (6~15자)\r\n");
      out.write("		if (form.nickname.value.length < 2 || form.nickname.value.length > 15) {\r\n");
      out.write("			alert(\"닉네임을 2~15자까지 입력해주세요.\")\r\n");
      out.write("			form.nickname.focus();\r\n");
      out.write("			form.nickname.select();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		 */\r\n");
      out.write("		var popupWidth = 650;\r\n");
      out.write("		var popupHeight = 250;\r\n");
      out.write("\r\n");
      out.write("		var popupX = (window.screen.width / 2) - (popupWidth / 2);\r\n");
      out.write("		// 만들 팝업창 width 크기의 1/2 만큼 보정값으로 빼주었음\r\n");
      out.write("\r\n");
      out.write("		var popupY= (window.screen.height / 2) - (popupHeight / 2);\r\n");
      out.write("		// 만들 팝업창 height 크기의 1/2 만큼 보정값으로 빼주었음\r\n");
      out.write("\r\n");
      out.write("		window.open(\"http://localhost:8081/SAII/saii/signup/nickcheck.jsp?nickname=\"+document.getElementById(\"usernickname\").value, \"chkForm\", \r\n");
      out.write("				'status=no, height=' + popupHeight  + ', width=' + popupWidth  + ', left='+ popupX + ', top='+ popupY);\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function idCk(){\r\n");
      out.write("		/* if(form.id.value == \"\"){\r\n");
      out.write("			alert(\"아이디를 입력하세요\");\r\n");
      out.write("			form.id.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		} */\r\n");
      out.write("		//아이디 길이 체크 (6~15자)\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		var popupWidth = 650;\r\n");
      out.write("		var popupHeight = 250;\r\n");
      out.write("\r\n");
      out.write("		var popupX = (window.screen.width / 2) - (popupWidth / 2);\r\n");
      out.write("		// 만들 팝업창 width 크기의 1/2 만큼 보정값으로 빼주었음\r\n");
      out.write("\r\n");
      out.write("		var popupY= (window.screen.height / 2) - (popupHeight / 2);\r\n");
      out.write("		// 만들 팝업창 height 크기의 1/2 만큼 보정값으로 빼주었음\r\n");
      out.write("	window.open(\"http://localhost:8081/SAII/saii/signup/idcheck.jsp?id=\"+document.getElementById(\"userId\").value, \"chkForm\", \r\n");
      out.write("			'status=no, height=' + popupHeight  + ', width=' + popupWidth  + ', left='+ popupX + ', top='+ popupY);\r\n");
      out.write("	    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		 \r\n");
      out.write("	}\r\n");
      out.write("	function goPopup(){\r\n");
      out.write("		// 주소검색을 수행할 팝업 페이지를 호출합니다.\r\n");
      out.write("		// 호출된 페이지(jusopopup.jsp)에서 실제 주소검색RL(https://business.juso.go.kr/addrlink/addrLinkUrl.do)를 호출하게 됩니다.\r\n");
      out.write("		var pop = window.open(\"http://localhost:8081/SAII/saii/juso.jsp\",\"pop\",\"width=570,height=420, scrollbars=yes, resizable=yes\"); \r\n");
      out.write("		\r\n");
      out.write("		// 모바일 웹인 경우, 호출된 페이지(jusopopup.jsp)에서 실제 주소검색URL(https://business.juso.go.kr/addrlink/addrMobileLinkUrl.do)를 호출하게 됩니다.\r\n");
      out.write("	  //var pop = window.open(\"/popup/jusoPopup.jsp\",\"pop\",\"scrollbars=yes, resizable=yes\"); \r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	function jusoCallBack(roadFullAddr){\r\n");
      out.write("			// 팝업페이지에서 주소입력한 정보를 받아서, 현 페이지에 정보를 등록합니다.\r\n");
      out.write("			document.getElementById(\"roadFullAddr\").value = roadFullAddr;\r\n");
      out.write("\r\n");
      out.write("			\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h2>회원가입</h2>\r\n");
      out.write("	<form id=\"form\" method=\"post\" action=\"http://localhost:8081/SAII/signup\" enctype=\"multipart/form-data\" onsubmit=\"return check();\">\r\n");
      out.write("										<!-- signupPageController로 이동                                             memAct.js로 이동  -->\r\n");
      out.write("	<div>\r\n");
      out.write("	<label>아이디 </label> \r\n");
      out.write("	<div class=\"ckck\">\r\n");
      out.write("	<input type=\"text\" id=\"userId\" name=\"id\"  placeholder=\"영문,숫자로 6~15자\" onclick=\"idCk(); \" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("	<button type=\"button\" class=\"ck-button\"  onclick=\"idCk(); \">확인</button> <br/>\r\n");
      out.write("											<!-- 위에 있음/ 빈칸인지 확인하고 창 열림 -->\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div>\r\n");
      out.write("	<label>비밀번호</label>\r\n");
      out.write("	<input type=\"password\" name=\"pw\" placeholder=\"영문,숫자로 8~15자\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.pw}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" ><br/>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div>\r\n");
      out.write("	<label>비밀번호 재확인</label>\r\n");
      out.write("	<input type=\"password\" name=\"pw2\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.pw2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/><br/>\r\n");
      out.write("	</div>\r\n");
      out.write("    \r\n");
      out.write("    <div>\r\n");
      out.write("    <label>닉네임</label>  \r\n");
      out.write("    <div class=\"ckck\">\r\n");
      out.write("	<input type=\"text\" id=\"usernickname\" name=\"nickname\" placeholder=\"입력하세요\"  onclick=\"nickCk();\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("	<button type=\"button\" class=\"ck-button\"  onclick=\"nickCk();\">확인</button> <br/>\r\n");
      out.write("	<!--  <input type=\"button\" value=\"중복체크\" onclick=\"nickCk();\"/> <br/> <br/>-->\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("    \r\n");
      out.write("    <div>\r\n");
      out.write("    <label>이름</label>  <br/>\r\n");
      out.write("    <input type=\"text\" name=\"name\" placeholder=\"한글만 입력 가능합니다.\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.name1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/><br/>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div>\r\n");
      out.write("    <label>성별</label>  <br/>\r\n");
      out.write("    <input type=\"radio\" name=\"sex\" value=\"여자\" checked/><a>여자</a>\r\n");
      out.write("    <input type=\"radio\" name=\"sex\" value=\"남자\" /><a>남자</a><br/> \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div>\r\n");
      out.write("    <label>생년월일</label> <br/>\r\n");
      out.write("    <select name=\"yy\" id=\"year\" ></select><a>년</a>\r\n");
      out.write("	<select name=\"mm\" id=\"month\" ></select><a>월</a>\r\n");
      out.write("	<select name=\"dd\" id=\"day\" ></select><a>일</a><br/>\r\n");
      out.write("	</div>\r\n");
      out.write("    \r\n");
      out.write("    <div>\r\n");
      out.write("    <label>프로필</label> <br/>\r\n");
      out.write("    <input type=\"file\" name=\"pick\" /><br/>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div>\r\n");
      out.write("    <label>주소</label> \r\n");
      out.write("    <input type=\"text\" id=\"roadFullAddr\" name=\"address\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" onClick=\"goPopup();\"> <br/>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div>\r\n");
      out.write("    <label>이메일</label> \r\n");
      out.write("    <input type=\"text\" name=\"email\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><br/>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div>\r\n");
      out.write("    <label>핸드폰번호</label>\r\n");
      out.write("    <input type=\"text\" name=\"phone\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><br/>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div>\r\n");
      out.write("    <div >\r\n");
      out.write("    <input class=\"sign\" type=\"submit\"  value=\"회원가입하기\" />\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    </form>\r\n");
      out.write("    \r\n");
      out.write("<script src=\"http://localhost:8081/SAII/saii/JS/memAct.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">* {cursor: url(https://ani.cursors-4u.net/symbols/sym-9/sym833.ani), url(https://ani.cursors-4u.net/symbols/sym-9/sym833.png), auto !important;}</style>\r\n");
      out.write("<a href=\"https://www.cursors-4u.com/cursor/2018/02/17/fast-beating-heart.html\" target=\"_blank\" title=\"Fast Beating Heart\"><img src=\"https://cur.cursors-4u.net/cursor.png\" border=\"0\" alt=\"Fast Beating Heart\" style=\"position:absolute; top: 0px; right: 0px;\" /></a>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
