/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-11-07 02:05:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.saii.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/saii/mypage/../top.jsp", Long.valueOf(1667782393323L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1667718152000L));
    _jspx_dependants.put("jar:file:/D:/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp4/wtpwebapps/SAII/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>마이페이지</title>\r\n");
      out.write("<script>\r\n");
      out.write("function passCk(){     \r\n");
      out.write("		\r\n");
      out.write("	var popupWidth = 650;\r\n");
      out.write("	var popupHeight = 250;\r\n");
      out.write("	\r\n");
      out.write("	var popupX = (window.screen.width / 2) - (popupWidth / 2);\r\n");
      out.write("	// 만들 팝업창 width 크기의 1/2 만큼 보정값으로 빼주었음\r\n");
      out.write("	\r\n");
      out.write("	var popupY= (window.screen.height / 2) - (popupHeight / 2);\r\n");
      out.write("	// 만들 팝업창 height 크기의 1/2 만큼 보정값으로 빼주었음\r\n");
      out.write("	\r\n");
      out.write("		window.open(\"http://localhost:8081/SAII/saii/mypage/passcheck.jsp?id=\"+document.getElementById(\"userId\").value, \"chkForm\", \r\n");
      out.write("				'width=' + popupWidth + ', height=' + popupHeight + ', resizable=no, scrollbars=no,top=' + popupY + ',left=' + popupX);\r\n");
      out.write("	}\r\n");
      out.write("function divshow1(){\r\n");
      out.write("	document.getElementById(\"show1\").style.display=\"block\";\r\n");
      out.write("	document.getElementById(\"show2\").style.display=\"none\";\r\n");
      out.write("	document.getElementById(\"show3\").style.display=\"none\";\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("function divshow2(){\r\n");
      out.write("	document.getElementById(\"show1\").style.display=\"none\";\r\n");
      out.write("	document.getElementById(\"show2\").style.display=\"block\";\r\n");
      out.write("	document.getElementById(\"show3\").style.display=\"none\";\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("function divshow3(){\r\n");
      out.write("	document.getElementById(\"show1\").style.display=\"none\";\r\n");
      out.write("	document.getElementById(\"show2\").style.display=\"none\";\r\n");
      out.write("	document.getElementById(\"show3\").style.display=\"block\";\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("function imgcg(input){\r\n");
      out.write("	if(input.files && input.files[0]){\r\n");
      out.write("		\r\n");
      out.write("		const reader = new FileReader()\r\n");
      out.write("        // 이미지가 로드가 된 경우\r\n");
      out.write("        reader.onload = function(e) {\r\n");
      out.write("            document.getElementById(\"preview\").src=e.target.result;\r\n");
      out.write("            document.getElementById(\"preview1\").src=e.target.result;\r\n");
      out.write("        };\r\n");
      out.write("     	// reader가 이미지 읽도록 하기\r\n");
      out.write("        reader.readAsDataURL(input.files[0]);\r\n");
      out.write("	}else{\r\n");
      out.write("		document.getElementById(\"preview\").src=\"/SAII/Storage/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.n_profile_img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("function withdrawcheck(){\r\n");
      out.write("	var memberdel = confirm('정말로 탈퇴하시겠습니까?');\r\n");
      out.write("	\r\n");
      out.write("	if(memberdel){\r\n");
      out.write("		alert('탈퇴됨');\r\n");
      out.write("		return true;\r\n");
      out.write("	}\r\n");
      out.write("	else{\r\n");
      out.write("		alert('탈퇴 안했네?');\r\n");
      out.write("		return false;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function imgoriginal(){\r\n");
      out.write("	   document.getElementById(\"preview1\").style.display=\"block\";\r\n");
      out.write("	}\r\n");
      out.write("function imgoriginalhidden(){\r\n");
      out.write("   document.getElementById(\"preview1\").style.display=\"none\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("#preview{\r\n");
      out.write("   transition-timing-function: ease-in;\r\n");
      out.write("}\r\n");
      out.write("#preview1{\r\n");
      out.write("   display: none;\r\n");
      out.write("   z-index: 1;\r\n");
      out.write("   position: absolute;\r\n");
      out.write("   top: 7%;\r\n");
      out.write("   transition: 2s;\r\n");
      out.write("   transition-timing-function: ease-in;\r\n");
      out.write("   max-height: 500px;\r\n");
      out.write("   max-width: 500px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#show2{\r\n");
      out.write("	display: none;\r\n");
      out.write("	width: 1000px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("}\r\n");
      out.write("#show3{\r\n");
      out.write("	display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr>td:first-child {\r\n");
      out.write("	text-align: right\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h3 {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("h2 {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#edit {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("	margin-top: 24px; \r\n");
      out.write("	height: 38px; \r\n");
      out.write("	width: 120px; \r\n");
      out.write("	left: 283px;\r\n");
      out.write("	background: none; \r\n");
      out.write("	border: none;\r\n");
      out.write("    color: #fff; \r\n");
      out.write("    font-size: 16px; \r\n");
      out.write("    font-weight: 500; \r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    border-radius: 4px; \r\n");
      out.write("    background-color: #98dde3;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input{\r\n");
      out.write("	outline:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#profile{\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	width: 300px;\r\n");
      out.write("	height: 300px;\r\n");
      out.write("	top: 100px;\r\n");
      out.write("	left: -250px;\r\n");
      out.write("}\r\n");
      out.write("#filebutton {\r\n");
      out.write("	display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input_file_button{\r\n");
      out.write("	position:relative;\r\n");
      out.write("	top:10px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	display:inline-block;\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("	margin-top: 24px; \r\n");
      out.write("	height: 30px; \r\n");
      out.write("	width: 120px; \r\n");
      out.write("	background: none; \r\n");
      out.write("	border: none;\r\n");
      out.write("    color: #fff; \r\n");
      out.write("    font-size: 16px; \r\n");
      out.write("    font-weight: 500; \r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    border-radius: 4px; \r\n");
      out.write("    background-color: #98dde3;\r\n");
      out.write("    padding-top: 8px;\r\n");
      out.write("}\r\n");
      out.write("#sub{\r\n");
      out.write("	display: none;\r\n");
      out.write("}\r\n");
      out.write(".input_submit{\r\n");
      out.write("	position:relative;\r\n");
      out.write("	top:14px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	display:inline-block;\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("	margin-top: 24px; \r\n");
      out.write("	height: 30px; \r\n");
      out.write("	width: 120px; \r\n");
      out.write("	background: none; \r\n");
      out.write("	border: none;\r\n");
      out.write("    color: #fff; \r\n");
      out.write("    font-size: 16px; \r\n");
      out.write("    font-weight: 500; \r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    border-radius: 4px; \r\n");
      out.write("    background-color: #98dde3;\r\n");
      out.write("    padding-top: 8px;\r\n");
      out.write("}\r\n");
      out.write("#mboard{\r\n");
      out.write("	position:relative;\r\n");
      out.write("	height: 300px;\r\n");
      out.write("	width: 818px;\r\n");
      out.write("	left: 50%;\r\n");
      out.write("	margin-left: -400px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".div1 {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".div1-1{\r\n");
      out.write("	width: 120px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	padding-top: 20px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	background-color: rgb(236,236,236);\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write("#del {\r\n");
      out.write("	display: none;\r\n");
      out.write("}\r\n");
      out.write(".withdraw{\r\n");
      out.write("	background-color: black;\r\n");
      out.write("	color: white;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	padding: 6px 25px;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	display:inline-block;\r\n");
      out.write("	width: 100px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mylabel{\r\n");
      out.write("	vertical-align: 5px; \r\n");
      out.write("	color: #999;\r\n");
      out.write("}\r\n");
      out.write(".mydiv{\r\n");
      out.write("	padding: 0px 0px 8px 0px;\r\n");
      out.write("}\r\n");
      out.write(".myinput{\r\n");
      out.write("	vertical-align: 5px; \r\n");
      out.write("	width:400px; \r\n");
      out.write("	height:40px; \r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	border:none; \r\n");
      out.write("	background-color: #F7F7F7;\r\n");
      out.write("}\r\n");
      out.write("#show1 {\r\n");
      out.write("	position:relative;\r\n");
      out.write("	width: 400px; \r\n");
      out.write("	margin:auto; \r\n");
      out.write("	padding:30px\r\n");
      out.write("}\r\n");
      out.write(".mylist{\r\n");
      out.write("	position: relative;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("	width: 500px;\r\n");
      out.write("	height: 150px;\r\n");
      out.write("	box-shadow: rgb(31 38 135 / 20%) 0px 8px 32px 0px;\r\n");
      out.write("	outline: 5px;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("	border-radius: 4px;\r\n");
      out.write("	top: 22px;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write(".mylist:hover{\r\n");
      out.write("	transform: scale(1.1) ;\r\n");
      out.write("    border: 10px;\r\n");
      out.write("    border-color: gray;\r\n");
      out.write("    background-color: #FFF4F9;\r\n");
      out.write("}\r\n");
      out.write(".imgdiv {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	left: 316px;\r\n");
      out.write("	top: 15px;\r\n");
      out.write("}\r\n");
      out.write(".spannick {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	top: -40px;\r\n");
      out.write("}\r\n");
      out.write(".divdate{\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	bottom: 2%;\r\n");
      out.write("	right: 3%;\r\n");
      out.write("}\r\n");
      out.write("span{\r\n");
      out.write("	color: #5075B5;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divtitle{\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 10%;\r\n");
      out.write("	left: 4%\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divregion{\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 10%;\r\n");
      out.write("	left: 58%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divname{\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 33%;\r\n");
      out.write("	left: 4%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divcount{\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 56%;\r\n");
      out.write("	left: 4%;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("a {\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write(".favoimg{\r\n");
      out.write("	position: relative;\r\n");
      out.write("	width:70px;\r\n");
      out.write("	height:70px;\r\n");
      out.write(" 	margin: auto;\r\n");
      out.write(" 	top: 32px;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write(".mylist2{\r\n");
      out.write("	position: relative;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("	width: 500px;\r\n");
      out.write("	height: 150px;\r\n");
      out.write("	box-shadow: rgb(31 38 135 / 20%) 0px 8px 32px 0px;\r\n");
      out.write("	outline: 5px;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("	border-radius: 4px;\r\n");
      out.write("	top:-70px;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write(".myfavo{\r\n");
      out.write("	height: 160px;\r\n");
      out.write("	width: 900px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("}\r\n");
      out.write(".mylist2:hover{\r\n");
      out.write("	transform: scale(1.1) ;\r\n");
      out.write("    border: 10px;\r\n");
      out.write("    border-color: gray;\r\n");
      out.write("    background-color: #FFF4F9;\r\n");
      out.write("}\r\n");
      out.write(".spanimg{\r\n");
      out.write("	position:relative;\r\n");
      out.write("\r\n");
      out.write("	top: 49px;\r\n");
      out.write("}\r\n");
      out.write(".favodiv{\r\n");
      out.write("	position: relative;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("	height: 150px;\r\n");
      out.write("	width: 240px;\r\n");
      out.write("	right: 355px;\r\n");
      out.write("	top: 78px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<style>\r\n");
      out.write("#abc {\r\n");
      out.write("	position:absolute;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	right: 2%;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write(".top_btn{\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("	margin-top: 24px; \r\n");
      out.write("	height: 30px; \r\n");
      out.write("	width: 120px; \r\n");
      out.write("	border: none;\r\n");
      out.write("    color: #fff; \r\n");
      out.write("    font-size: 16px; \r\n");
      out.write("    font-weight: 500; \r\n");
      out.write("    border-radius: 4px; \r\n");
      out.write("    background-color: #98dde3;\r\n");
      out.write("    padding: 8px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<img id=himg src=\"http://localhost:8081/SAII/saii/img/saii.png\" width=60px; height=40px; onclick='location.href=\"http://localhost:8081/SAII/home\"';>\r\n");
      out.write("<div id=\"abc\">\r\n");
      out.write("	<a class=\"top_btn\" href=\"javascript:window.history.back();\">뒤로가기</a>\r\n");
      out.write("	<a  class=\"top_btn\" href=\"http://localhost:8081/SAII/mainboard?page=1\">전체게시판</a>\r\n");
      out.write("	<a  class=\"top_btn\" href=\"http://localhost:8081/SAII/review_list\">리뷰게시판</a>\r\n");
      out.write("	\r\n");
      out.write("	");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">* {cursor: url(https://ani.cursors-4u.net/symbols/sym-9/sym833.ani), url(https://ani.cursors-4u.net/symbols/sym-9/sym833.png), auto !important;}</style>\r\n");
      out.write("<a href=\"https://www.cursors-4u.com/cursor/2018/02/17/fast-beating-heart.html\" target=\"_blank\" title=\"Fast Beating Heart\"><img src=\"https://cur.cursors-4u.net/cursor.png\" border=\"0\" alt=\"Fast Beating Heart\" style=\"position:absolute; top: 0px; right: 0px;\" /></a>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<h3>마이페이지</h3>\r\n");
      out.write("<div class=\"div1\">\r\n");
      out.write("	<div class=\"div1-1\" onclick=\"divshow1()\">내 정보</div>\r\n");
      out.write("	<div class=\"div1-1\" onclick=\"divshow2()\">내가 만든 코스</div>\r\n");
      out.write("	<div class=\"div1-1\" onclick=\"divshow3()\">내가 찜한 코스</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"show1\" >\r\n");
      out.write("	<form method=\"get\" onsubmit=\"passCk()\">\r\n");
      out.write("	<input id=\"edit\" type=\"submit\" value=\"수정하러가기\" >\r\n");
      out.write("	<div class=\"mydiv\">\r\n");
      out.write("	<label class=\"mylabel\">아이디</label><br/>\r\n");
      out.write("	<input class=\"myinput\" type=\"text\" id=\"userId\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"mydiv\">\r\n");
      out.write("	<label class=\"mylabel\">비밀번호</label><br/>\r\n");
      out.write("	<input class=\"myinput\" type=\"password\" name=\"pw\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.pw }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"mydiv\">\r\n");
      out.write("	<label class=\"mylabel\">닉네임</label><br/>\r\n");
      out.write("	<input class=\"myinput\" type=\"text\" name=\"nickname\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.nickname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"readonly>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"mydiv\">\r\n");
      out.write("	<label class=\"mylabel\">이름</label><br/>\r\n");
      out.write("	<input class=\"myinput\" type=\"text\" name=\"name\"	value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"mydiv\">\r\n");
      out.write("	<label class=\"mylabel\">생년월일</label><br/>\r\n");
      out.write("	<input class=\"myinput\" type=\"Date\" name=\"birthday\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.birthday }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"mydiv\">\r\n");
      out.write("	<label class=\"mylabel\">성별</label><br/>\r\n");
      out.write("	<input class=\"myinput\" type=\"text\" name=\"sex\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.sex }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"mydiv\">\r\n");
      out.write("	<label class=\"mylabel\">전화</label><br/>\r\n");
      out.write("	<input class=\"myinput\" type=\"text\" name=\"phone\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.phone }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"mydiv\">\r\n");
      out.write("	<label class=\"mylabel\">이메일</label><br/>\r\n");
      out.write("	<input class=\"myinput\" type=\"email\" name=\"email\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"mydiv\">\r\n");
      out.write("	<label class=\"mylabel\">주소</label><br/>\r\n");
      out.write("	<input class=\"myinput\" type=\"text\" name=\"address\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.address }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"readonly>\r\n");
      out.write("	</div>\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	</table>\r\n");
      out.write("	<div id=\"profile\" align=\"center\">\r\n");
      out.write("	<img id=\"preview\" src=\"/SAII/Storage/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.n_profile_img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" width=\"120px\" height=\"120px\" style=\"border-radius: 50px\" onclick=\"imgoriginal()\">\r\n");
      out.write("	<form action=\"http://localhost:8081/SAII/upload?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"img\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("		<input type=\"hidden\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("		<label class=\"input_file_button\" for=\"filebutton\">사진선택</label>\r\n");
      out.write("		<input id=\"filebutton\" type=\"file\" name=\"o_profile_img\" onchange=\"imgcg(this)\" required><br>\r\n");
      out.write("		<label class=\"input_submit\" for=\"sub\">프로필 변경</label>\r\n");
      out.write("		<input id=\"sub\" type=\"submit\" value=\"프로필변경\">\r\n");
      out.write("	</form>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<img id=\"preview1\" src=\"/SAII/Storage/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.n_profile_img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" onclick=\"imgoriginalhidden()\">\r\n");
      out.write("<div id=\"show2\">\r\n");
      out.write("	<div class=\"imgdiv\">\r\n");
      out.write("		<img src=\"/SAII/Storage/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.n_profile_img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" width=\"90px\" height=\"90px\" style=\"border-radius: 50px\">\r\n");
      out.write("		<span class=\"spannick\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님의 코스 갯수 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.mylistcount }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("	</div>\r\n");
      out.write("	");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"show3\">\r\n");
      out.write("	");
      if (_jspx_meth_c_005fchoose_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("	<form action=\"http://localhost:8081/SAII/withdraw\" onsubmit=\"return withdrawcheck()\">\r\n");
      out.write("		<input type=\"submit\" id=\"del\" >\r\n");
      out.write("		<label class=\"withdraw\" for=\"del\" >회원탈퇴</label>	\r\n");
      out.write("	</form>\r\n");
      out.write("</div>\r\n");
      out.write("<a href=\"http://localhost:8081/SAII/home\">돌아가기</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--마우스 커서-->\r\n");
      out.write("<style type=\"text/css\">* {cursor: url(https://ani.cursors-4u.net/symbols/sym-9/sym833.ani), url(https://ani.cursors-4u.net/symbols/sym-9/sym833.png), auto !important;}</style>\r\n");
      out.write("<a href=\"https://www.cursors-4u.com/cursor/2018/02/17/fast-beating-heart.html\" target=\"_blank\" title=\"Fast Beating Heart\"><img src=\"https://cur.cursors-4u.net/cursor.png\" border=\"0\" alt=\"Fast Beating Heart\" style=\"position:absolute; top: 0px; right: 0px;\" /></a>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /saii/mypage/../top.jsp(40,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${UserId!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<a class=\"top_btn\" href=\"http://localhost:8081/SAII/mypage?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${UserId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">마이 페이지</a>");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /saii/mypage/../top.jsp(41,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${UserId==null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<a class=\"top_btn\" href=\"http://localhost:8081/SAII/login\">로그인</a>");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /saii/mypage/../top.jsp(42,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${UserId!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<a class=\"top_btn\" href=\"http://localhost:8081/SAII/logout\">로그아웃</a>");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("		");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          out.write('	');
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /saii/mypage/myPage.jsp(428,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty list }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			");
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fwhen_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f0);
      // /saii/mypage/myPage.jsp(429,3) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/saii/mypage/myPage.jsp(429,3) '${list}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /saii/mypage/myPage.jsp(429,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("mlist");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("				<div class=\"mylist\">\r\n");
            out.write("					<a href=\"http://localhost:8081/SAII/view?m_id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${miist.m_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("						<div class=\"divtitle\"><span>코스이름 </span> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mlist.m_title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("						<div class=\"divregion\"><span>코스지역 </span> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mlist.region}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("						<div class=\"divname\"><span>코스경로 </span> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mlist.pname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("						<div class=\"divdate\"><span>게시날짜 </span> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mlist.m_postdate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("						<div class=\"divcount\"><span>선택장소 </span> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mlist.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("					</a>\r\n");
            out.write("				</div>\r\n");
            out.write("			");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			<div>등록된 게시물이 없어요~</div>\r\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent(null);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("		");
          if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          out.write('	');
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /saii/mypage/myPage.jsp(449,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty flist }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			");
          if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fwhen_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f1);
      // /saii/mypage/myPage.jsp(450,3) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/saii/mypage/myPage.jsp(450,3) '${flist}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${flist}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /saii/mypage/myPage.jsp(450,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("flist2");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("			<div class=\"myfavo\">\r\n");
            out.write("				<div class=\"favodiv\">\r\n");
            out.write("					<img class=\"favoimg\"src=\"/SAII/Storage/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${flist2.profile}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"  style=\"border-radius: 50px\">\r\n");
            out.write("					<br><span class=\"spanimg\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${flist2.nickname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("의 게시물</span>\r\n");
            out.write("				</div>\r\n");
            out.write("				<div class=\"mylist2\">\r\n");
            out.write("					<a href=\"http://localhost:8081/SAII/view?m_id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${flist2.m_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("						<div class=\"divtitle\"><span>코스이름 </span> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${flist2.m_title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("						<div class=\"divregion\"><span>코스지역 </span> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${flist2.region}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("						<div class=\"divname\"><span>코스경로 </span> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${flist2.pname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("						<div class=\"divdate\"><span>게시날짜 </span> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${flist2.m_postdate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("						<div class=\"divcount\"><span>선택장소 </span> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${flist2.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("					</a>\r\n");
            out.write("				</div>\r\n");
            out.write("			</div>\r\n");
            out.write("			");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f1_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			<div>좋아요 누른 코스가 없어요~</div>\r\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      _jspx_th_c_005fotherwise_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f1_reused);
    }
    return false;
  }
}
